export const endpoints =
  [
    { id: 1, name: "accounts", descr: "Аккаунты пользователей",ep0:"accounts",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 2, name: "accounts/2723d6dd-1a53-4ce3-a3fd-c7c4203aefef", descr: "Аккаунты пользователей",ep0:"accounts",id0:"2723d6dd-1a53-4ce3-a3fd-c7c4203aefef",ep1:"",id1:"",ep2:"",id2:""},
    { id: 3, name: "affiliates", descr: "Каталог филиалов",ep0:"affiliates",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 4, name: "affiliates/1", descr: "Каталог филиалов",ep0:"affiliates",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 5, name: "agents", descr: "Каталог агентов",ep0:"agents",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 6, name: "agents/1", descr: "Каталог агентов",ep0:"agents",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 7, name: "cabin-exclude-groups", descr: "Название блокировки",ep0:"cabin-exclude-groups",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 8, name: "cabin-exclude-groups/1", descr: "Название блокировки",ep0:"cabin-exclude-groups",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 9, name: "cabin-excludes", descr: "Блокировки",ep0:"cabin-excludes",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 10, name: "cabin-excludes/1", descr: "Блокировки",ep0:"cabin-excludes",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 11, name: "cabins", descr: "Каталог кают",ep0:"cabins",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 12, name: "cabins/1", descr: "Каталог кают",ep0:"cabins",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 13, name: "cities", descr: "Города",ep0:"cities",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 14, name: "cities/1", descr: "Города",ep0:"cities",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 15, name: "cities/1/agents", descr: "Агентства в городе",ep0:"cities",id0:"1",ep1:"agents",id1:"",ep2:"",id2:""},
    { id: 16, name: "cities/1/agents/2", descr: "Агентства в городе",ep0:"cities",id0:"1",ep1:"agents",id1:"2",ep2:"",id2:""},
    { id: 17, name: "cities/1/agents/1", descr: "Агентства в городе",ep0:"cities",id0:"1",ep1:"agents",id1:"1",ep2:"",id2:""},
    { id: 18, name: "cities/1/tours", descr: "Туры через город",ep0:"cities",id0:"1",ep1:"tours",id1:"",ep2:"",id2:""},
    { id: 19, name: "cities/1/tours/1", descr: "Туры через город",ep0:"cities",id0:"1",ep1:"tours",id1:"1",ep2:"",id2:""},
    { id: 20, name: "cities/1/tours", descr: "Туры через город",ep0:"cities",id0:"1",ep1:"tours",id1:"",ep2:"",id2:""},
    { id: 21, name: "cities/logs", descr: "Логи изменения таблицы Города",ep0:"cities",id0:"",ep1:"logs",id1:"",ep2:"",id2:""},
    { id: 22, name: "cities/logs/1", descr: "Логи изменения таблицы Города",ep0:"cities",id0:"",ep1:"logs",id1:"1",ep2:"",id2:""},
    { id: 23, name: "collections", descr: "Получить абсолютно все справочники",ep0:"collections",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 24, name: "collections/1", descr: "Получить абсолютно все справочники",ep0:"collections",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 25, name: "companies", descr: "Каталог компаний",ep0:"companies",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 26, name: "companies/1", descr: "Каталог компаний",ep0:"companies",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 27, name: "contractors", descr: "Каталог контрагентов",ep0:"contractors",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 28, name: "contractors/1", descr: "Каталог контрагентов",ep0:"contractors",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 29, name: "employees", descr: "Каталог сотрудников",ep0:"employees",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 30, name: "employees/96", descr: "Каталог сотрудников",ep0:"employees",id0:"96",ep1:"",id1:"",ep2:"",id2:""},
    { id: 31, name: "excursions", descr: "Экскурсии",ep0:"excursions",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 32, name: "excursions/1", descr: "Экскурсии",ep0:"excursions",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 33, name: "expired-orders", descr: "Аннулированные брони",ep0:"expired-orders",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 34, name: "expired-orders/1", descr: "Аннулированные брони",ep0:"expired-orders",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 35, name: "holidays", descr: "",ep0:"holidays",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 36, name: "holidays/1", descr: "",ep0:"holidays",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 37, name: "legal-entities", descr: "Каталог юр.лиц",ep0:"legal-entities",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 38, name: "legal-entities/1", descr: "Каталог юр.лиц",ep0:"legal-entities",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 39, name: "lost-cabins", descr: "Потерянные каюты",ep0:"lost-cabins",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 40, name: "lost-cabins/1", descr: "Потерянные каюты",ep0:"lost-cabins",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 41, name: "orders", descr: "Брони",ep0:"orders",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 42, name: "orders/100600000", descr: "Брони",ep0:"orders",id0:"100600000",ep1:"",id1:"",ep2:"",id2:""},
    { id: 43, name: "orders/100600000/order-cabins", descr: "Каюты в заказе",ep0:"orders",id0:"100600000",ep1:"order-cabins",id1:"",ep2:"",id2:""},
    { id: 44, name: "orders/100600000/order-cabins", descr: "Каюты в заказе",ep0:"orders",id0:"100600000",ep1:"order-cabins",id1:"",ep2:"",id2:""},
    { id: 45, name: "orders/100600000/order-cabins/1/order-places", descr: "Места в каюте в заказе",ep0:"orders",id0:"100600000",ep1:"order-cabins",id1:"1",ep2:"order-places",id2:""},
    { id: 46, name: "orders/100600000/order-cabins/1/order-places/1", descr: "Места в каюте в заказе",ep0:"orders",id0:"100600000",ep1:"order-cabins",id1:"1",ep2:"order-places",id2:"1"},
    { id: 47, name: "physical-persons", descr: "Каталог физлиц",ep0:"physical-persons",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 48, name: "physical-persons/2", descr: "Каталог физлиц",ep0:"physical-persons",id0:"2",ep1:"",id1:"",ep2:"",id2:""},
    { id: 49, name: "physical-persons/logs", descr: "Каталог физлиц",ep0:"physical-persons",id0:"",ep1:"logs",id1:"",ep2:"",id2:""},
    { id: 50, name: "physical-persons/logs/1", descr: "Каталог физлиц",ep0:"physical-persons",id0:"",ep1:"logs",id1:"1",ep2:"",id2:""},
    { id: 51, name: "places", descr: "Каталог мест",ep0:"places",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 52, name: "places/1", descr: "Каталог мест",ep0:"places",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 53, name: "regions", descr: "Регионы",ep0:"regions",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 54, name: "regions/1", descr: "Регионы",ep0:"regions",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 55, name: "ship-cabin-classes", descr: "Каталог классов кают",ep0:"ship-cabin-classes",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 56, name: "ship-cabin-classes/1", descr: "Каталог классов кают",ep0:"ship-cabin-classes",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 57, name: "ships", descr: "Корабли",ep0:"ships",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 58, name: "ships/1", descr: "Корабли",ep0:"ships",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 59, name: "ships/1/cabins", descr: "",ep0:"ships",id0:"1",ep1:"cabins",id1:"",ep2:"",id2:""},
    { id: 60, name: "ships/1/cabins/1", descr: "",ep0:"ships",id0:"1",ep1:"cabins",id1:"1",ep2:"",id2:""},
    { id: 61, name: "ships-teams", descr: "Группы кораблей",ep0:"ships-teams",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 62, name: "ships-teams/1", descr: "Группы кораблей",ep0:"ships-teams",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 63, name: "temporal-orders", descr: "Временные брони",ep0:"temporal-orders",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 64, name: "temporal-orders/1", descr: "Временные брони",ep0:"temporal-orders",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 65, name: "tourists", descr: "Туристы",ep0:"tourists",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 66, name: "tourists/1", descr: "Туристы",ep0:"tourists",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 67, name: "tours", descr: "Туры",ep0:"tours",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 68, name: "tours/1", descr: "Туры",ep0:"tours",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 69, name: "tours/1/tour-cabin-prices", descr: "",ep0:"tours",id0:"1",ep1:"tour-cabin-prices",id1:"",ep2:"",id2:""},
    { id: 70, name: "tours/1/tour-cabin-prices", descr: "",ep0:"tours",id0:"1",ep1:"tour-cabin-prices",id1:"",ep2:"",id2:""},
    { id: 71, name: "tours/1/tour-exclude-navigation", descr: "",ep0:"tours",id0:"1",ep1:"tour-exclude-navigation",id1:"",ep2:"",id2:""},
    { id: 72, name: "tours/1/tour-exclude-navigation/1", descr: "",ep0:"tours",id0:"1",ep1:"tour-exclude-navigation",id1:"1",ep2:"",id2:""},
    { id: 73, name: "virtuals-cabins", descr: "Каталог виртуальных кают, или каюты на подселение",ep0:"virtuals-cabins",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 74, name: "virtuals-cabins/1", descr: "Каталог виртуальных кают, или каюты на подселение",ep0:"virtuals-cabins",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    { id: 75, name: "waiting", descr: "Лист ожидания",ep0:"waiting",id0:"",ep1:"",id1:"",ep2:"",id2:""},
    { id: 76, name: "waiting/1", descr: "Лист ожидания",ep0:"waiting",id0:"1",ep1:"",id1:"",ep2:"",id2:""},
    
  ];

export default {
  getendpoints() {
    return endpoints;
  },
};
